dbt_cap:
  outputs:
    dev:
      dataset: transforms
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/gcs_keyfile.json # in airflow container
      location: US
      method: service-account
      priority: interactive
      project: alt-de-capstone
      threads: 1
      type: bigquery
  target: dev